module.exports = Object.freeze({
  PRIMARY_COLOR: '#000',
  SECONDARY_COLOR: '#08c',
  HEADER_COLOR: '#3bf',
  HEADER_TEXT_COLOR: '#000',
  DROPDOWN_BACKGROUND: '#eee',
  DROPDOWN_HOVER_BACKGROUND: '#918',
  DROPDOWN_HOVER_TEXT: 'white'
})
